language: cpp
compiler: gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y scons python-jinja2 libsdl1.2-dev
 - sudo apt-get install -y python3
before_script:
 - sudo apt-get install -y software-properties-common
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:mapnik/boost
 - sudo apt-get update -qq
 - sudo apt-get install -y gcc-arm-none-eabi gcc-avr binutils-avr avr-libc
 - sudo apt-get install -y g++-4.8
 - sudo apt-get install -y libboost1.49-dev libboost-system1.49-dev
 - sudo apt-get install -y libboost-thread1.49-dev
 - export CC=gcc-4.8
 - export CXX=g++-4.8

script:
 - scons check
 - scons unittest
