language: cpp
compiler: gcc
sudo: required
dist: trusty

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - python
   - libsdl1.2-dev
   - libsdl-image1.2-dev
   - libgtkmm-2.4-dev
   - g++-4.8
   - lib32z1
   - lib32ncurses5
   - lib32bz2-1.0
   - libzmqpp-dev

before_install:
 - export CC=gcc-4.8
 - export CXX=g++-4.8
 - bash .travis.dep.sh
 - export LD_LIBRARY_PATH="$HOME/cache/boost/lib:$LD_LIBRARY_PATH"
 - export CXXFLAGS="-isystem$HOME/cache/boost/include"
 - export LDFLAGS="-L$HOME/cache/boost/lib"
 - export PATH="$HOME/cache/avr8-gnu-toolchain-linux_x86/bin:$HOME/cache/gcc-arm-none-eabi-6-2017-q2-update/bin:$PATH"
 - echo $PATH
 - ls -l $HOME/cache/avr8-gnu-toolchain-linux_x86/bin
 - ls -l $HOME/cache/gcc-arm-none-eabi-6-2017-q2-update/bin
 - ls -l $HOME/cache/boost
 - which avr-g++
 - avr-g++ --version
 - which arm-none-eabi-g++
 - arm-none-eabi-g++ --version
 - pip install --upgrade pip wheel
 - pip install jinja2 lxml
 - pip install --egg SCons

cache:
 directories:
  - $HOME/cache

# these are ordered by longest running time, so that all instances complete
# within the longest running instances, which is the first.
env:
 - TEST_SUITE="check=examples examples=stm32f4_discovery"
 - TEST_SUITE="check=examples examples=stm32f3_discovery"
 - TEST_SUITE="unittest"
 - TEST_SUITE="unittest target=stm32"
 - TEST_SUITE="unittest target=atmega"
 - TEST_SUITE="check=examples examples=avr"
 - TEST_SUITE="check=devices"
 - TEST_SUITE="check=examples examples=linux"
 - TEST_SUITE="check=examples examples=stm32f429_discovery"
 - TEST_SUITE="check=examples examples=stm32f1_discovery"
 - TEST_SUITE="check=examples examples=stm32f072_discovery"
 - TEST_SUITE="check=examples examples=lpcxpresso"
 - TEST_SUITE="check=examples examples=stm32"
 - TEST_SUITE="check=examples examples=arduino_uno"
 - TEST_SUITE="check=examples examples=stm32f746g_discovery"
 - TEST_SUITE="check=examples examples=stm32f4_loa_v2b"
 - TEST_SUITE="check=examples examples=stm32f469_discovery"
 - TEST_SUITE="check=examples examples=stm32l476_discovery"
 - TEST_SUITE="check=examples examples=nucleo_f031k6"
 - TEST_SUITE="check=examples examples=nucleo_f103rb"
 - TEST_SUITE="check=examples examples=nucleo_f303k8"
 - TEST_SUITE="check=examples examples=nucleo_f401re"
 - TEST_SUITE="check=examples examples=nucleo_f411re"
 - TEST_SUITE="check=examples examples=nucleo_f429zi"
 - TEST_SUITE="check=examples examples=nucleo_l476rg"
 - TEST_SUITE="check=examples examples=unittest"
 - TEST_SUITE="check=examples examples=zmq"

script: "scons $TEST_SUITE"
