language: cpp
compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y software-properties-common
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:mapnik/boost
 - sudo apt-get update -qq
 - sudo apt-get install -y scons python python-jinja2 python-lxml
 - sudo apt-get install -y libsdl1.2-dev libsdl-image1.2-dev libgtkmm-2.4-dev
 - sudo apt-get install -y gcc-arm-none-eabi g++-4.8
 - sudo apt-get install -y libboost1.49-dev libboost-system1.49-dev libboost-thread1.49-dev
 - export CC=gcc-4.8
 - export CXX=g++-4.8
 - wget http://www.atmel.com/images/avr8-gnu-toolchain-3.4.5.1522-linux.any.x86.tar.gz -O avr8.tar.gz
 - tar -zxf avr8.tar.gz
 - export PATH="$PATH:$TRAVIS_BUILD_DIR/avr8-gnu-toolchain-linux_x86/bin"

env:
 - TEST_SUITE="unittest"
 - TEST_SUITE="check=devices"
 - TEST_SUITE="check=examples examples=arduino_uno"
 - TEST_SUITE="check=examples examples=avr"
 - TEST_SUITE="check=examples examples=linux"
 - TEST_SUITE="check=examples examples=lpcxpresso"
 - TEST_SUITE="check=examples examples=stm32"
 - TEST_SUITE="check=examples examples=stm32f1_discovery"
 - TEST_SUITE="check=examples examples=stm32f3_discovery"
 - TEST_SUITE="check=examples examples=stm32f4_discovery"
 - TEST_SUITE="check=examples examples=stm32f429_discovery"
 - TEST_SUITE="check=examples examples=stm32f7_discovery"
 - TEST_SUITE="check=examples examples=stm32f4_loa_v2b"
 - TEST_SUITE="check=examples examples=unittest"

script: "scons $TEST_SUITE"
