language: cpp
compiler: gcc
sudo: required
dist: trusty

group: deprecated-2017Q3

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - python
   - libsdl1.2-dev
   - libsdl-image1.2-dev
   - libgtkmm-2.4-dev
   - g++-4.8
   - libzmqpp-dev

before_install:
 - export CC=gcc-4.8
 - export CXX=g++-4.8
 - ls -l $HOME/cache
 - bash .travis.dep.sh
 - export LD_LIBRARY_PATH="$HOME/toolchain/boost/lib:$LD_LIBRARY_PATH"
 - export CXXFLAGS="-isystem$HOME/toolchain/boost/include"
 - export LDFLAGS="-L$HOME/toolchain/boost/lib"
 - export PATH="$HOME/toolchain/avr-gcc/bin:$HOME/toolchain/gcc-arm-none-eabi-6-2017-q2-update/bin:$PATH"
 - echo $PATH
 - ls -l $HOME/toolchain
 - ls -l $HOME/toolchain/avr-gcc/bin
 - ls -l $HOME/toolchain/gcc-arm-none-eabi-6-2017-q2-update/bin
 - ls -l $HOME/toolchain/boost
 - which avr-g++
 - avr-g++ --version
 - which arm-none-eabi-g++
 - arm-none-eabi-g++ --version
 - pip install --upgrade pip wheel
 - pip install jinja2 lxml
 - pip install --egg SCons

cache:
 directories:
  - $HOME/cache

# these are ordered by longest running time, so that all instances complete
# within the longest running instances, which is the first.
env:
 - TEST_SUITE="check=examples examples=stm32f4_discovery"
 - TEST_SUITE="check=examples examples=stm32f469_discovery,lpcxpresso,linux,unittest"
 - TEST_SUITE="check=examples examples=stm32,stm32f3_discovery,stm32f429_discovery,stm32f1_discovery,stm32f0_discovery,stm32f072_discovery,stm32f746g_discovery,stm32l476_discovery"
 - TEST_SUITE="check=examples examples=avr,arduino_uno,zmq"
 - TEST_SUITE="check=devices"
 - TEST_SUITE="check=examples examples=nucleo_f031k6,nucleo_f103rb,nucleo_f303k8,nucleo_f401re,nucleo_f411re,nucleo_f429zi,nucleo_l476rg,olimexino_stm32"
 - TEST_SUITE="unittest"
 - TEST_SUITE="unittest target=stm32"
 - TEST_SUITE="unittest target=atmega"

script: "scons $TEST_SUITE"
